# Generated by Django 5.2.11 on 2026-02-10 02:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artists', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('slug', models.SlugField(blank=True, max_length=550, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_time', models.DateTimeField()),
                ('venue', models.CharField(max_length=300)),
                ('city', models.CharField(max_length=100)),
                ('state_province', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(default='US', max_length=2)),
                ('ticket_url', models.URLField(blank=True, max_length=500, null=True)),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('ticketmaster', 'Ticketmaster')], default='manual', max_length=20)),
                ('ticketmaster_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='artists.artistgroup')),
            ],
            options={
                'ordering': ['date_time'],
                'indexes': [models.Index(fields=['date_time'], name='idx_event_date_time'), models.Index(fields=['city'], name='idx_event_city')],
            },
        ),
    ]
