openapi: 3.1.0
info:
  title: K-Pop Event Hub API (Lean MVP)
  version: 2.0.0

servers:
  - url: /api/v1

paths:
  /events:
    get:
      summary: List events
      operationId: listEvents
      parameters:
        - name: page
          in: query
          schema: { type: integer, default: 1 }
        - name: page_size
          in: query
          schema: { type: integer, default: 20, maximum: 50 }
        - name: city
          in: query
          schema: { type: string }
        - name: month
          in: query
          schema: { type: integer, minimum: 1, maximum: 12 }
        - name: year
          in: query
          schema: { type: integer }
        - name: featured
          in: query
          schema: { type: boolean }
      responses:
        '200':
          description: Paginated event list
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EventListResponse'

  /events/{slug}:
    get:
      summary: Get event detail
      operationId: getEvent
      parameters:
        - name: slug
          in: path
          required: true
          schema: { type: string }
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EventDetail'
        '404':
          description: Not found

  /groups:
    get:
      summary: List artist groups
      operationId: listGroups
      parameters:
        - name: page
          in: query
          schema: { type: integer, default: 1 }
        - name: page_size
          in: query
          schema: { type: integer, default: 50 }
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GroupListResponse'

  /groups/{slug}:
    get:
      summary: Get group detail
      operationId: getGroup
      parameters:
        - name: slug
          in: path
          required: true
          schema: { type: string }
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GroupDetail'
        '404':
          description: Not found

  /cities:
    get:
      summary: List cities with upcoming events
      operationId: listCities
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items: { type: string }

  /subscribers:
    post:
      summary: Subscribe by email
      operationId: createSubscriber
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SubscriberCreate'
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SubscriberResponse'
        '400':
          description: Validation error

  /subscribers/unsubscribe:
    post:
      summary: Unsubscribe by token
      operationId: unsubscribe
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                token: { type: string }
              required: [token]
      responses:
        '200':
          description: Unsubscribed

components:
  schemas:
    EventSummary:
      type: object
      properties:
        id: { type: string, format: uuid }
        title: { type: string }
        slug: { type: string }
        date_time: { type: string, format: date-time }
        venue: { type: string }
        city: { type: string }
        image_url: { type: string }
        group:
          $ref: '#/components/schemas/GroupSummary'
        is_featured: { type: boolean }
      required: [id, title, slug, date_time, venue, city]

    EventDetail:
      allOf:
        - $ref: '#/components/schemas/EventSummary'
        - type: object
          properties:
            description: { type: string }
            state_province: { type: string }
            country: { type: string }
            ticket_url: { type: string }
            source: { type: string, enum: [manual, ticketmaster] }

    EventListResponse:
      type: object
      properties:
        results:
          type: array
          items:
            $ref: '#/components/schemas/EventSummary'
        count: { type: integer }
        next: { type: string }
        previous: { type: string }
      required: [results, count]

    GroupSummary:
      type: object
      properties:
        id: { type: string, format: uuid }
        name: { type: string }
        slug: { type: string }
        image_url: { type: string }
      required: [id, name, slug]

    GroupDetail:
      allOf:
        - $ref: '#/components/schemas/GroupSummary'
        - type: object
          properties:
            description: { type: string }
            is_active: { type: boolean }

    GroupListResponse:
      type: object
      properties:
        results:
          type: array
          items:
            $ref: '#/components/schemas/GroupSummary'
        count: { type: integer }
        next: { type: string }
        previous: { type: string }
      required: [results, count]

    SubscriberCreate:
      type: object
      properties:
        email: { type: string, format: email }
      required: [email]

    SubscriberResponse:
      type: object
      properties:
        id: { type: string, format: uuid }
        email: { type: string }
        created_at: { type: string, format: date-time }
